Repository hashicorp/consul-template, pull requests merged in 2019-07, with the labels that each got.

#1226 fix broken default config tests
  config/config_test.go
Labels: bug

#1227 once-wait-conflict
  README.md
  cli.go
  cli_test.go
  config/config.go
  config/config_test.go
  manager/runner.go
  manager/runner_test.go
Labels: bug

#1168 change dedup to use one key and do auto-cleanup of the dedup kv store
  manager/dedup.go
Labels: bug, dedup

#1139 fixed burntsushi/toml import path
  Gopkg.lock
  Gopkg.toml
  template/funcs.go
  vendor/github.com/BurntSushi/toml/.gitignore
  vendor/github.com/BurntSushi/toml/.travis.yml
  vendor/github.com/BurntSushi/toml/COMPATIBLE
  vendor/github.com/BurntSushi/toml/COPYING
  vendor/github.com/BurntSushi/toml/Makefile
  vendor/github.com/BurntSushi/toml/README.md
  vendor/github.com/BurntSushi/toml/decode.go
  vendor/github.com/BurntSushi/toml/decode_meta.go
  vendor/github.com/BurntSushi/toml/decode_test.go
  vendor/github.com/BurntSushi/toml/doc.go
  vendor/github.com/BurntSushi/toml/encode.go
  vendor/github.com/BurntSushi/toml/encode_test.go
  vendor/github.com/BurntSushi/toml/encoding_types.go
  vendor/github.com/BurntSushi/toml/encoding_types_1.1.go
  vendor/github.com/BurntSushi/toml/lex.go
  vendor/github.com/BurntSushi/toml/parse.go
  vendor/github.com/BurntSushi/toml/session.vim
  vendor/github.com/BurntSushi/toml/type_check.go
  vendor/github.com/BurntSushi/toml/type_fields.go
Labels: bug

#1236 forward compatibility with vault env name change
  config/vault.go
Labels: vault

#1200 add ca-certificates to light docker image
  docker/light/Dockerfile
Labels: bug, vault

#1230 tests now use an external vault process
  .circleci/config.yml
  README.md
  dependency/client_set_test.go
  dependency/dependency_test.go
  dependency/vault_agent_token_test.go
  dependency/vault_list_test.go
  dependency/vault_read_test.go
  dependency/vault_write.go
  dependency/vault_write_test.go
Labels: vault

#1238 fix test issues due to meta data added to consul
  dependency/catalog_node_test.go
  dependency/catalog_service_test.go
  dependency/consul_common_test.go
  dependency/health_service_test.go
Labels: bug, consul

#1241 init quiescence after all templates are rendered
  manager/runner.go
  manager/runner_test.go
Labels: bug
