Repository hashicorp/consul-template, pull requests merged in 2019-12, with the labels that each got.

#1315 Remove extra whitespace from sockaddr func
  template/funcs.go
  template/template_test.go
Labels: bug

#1318 Fix documentation for default exec kill signal.
  README.md
  config/exec.go
Labels: bug, docs

#1309 Add DEBUG messages to identify missing dependencies
  manager/runner.go
Labels: enhancement

#1284 Remove code/logic for working with Vault grace
  cli.go
  cli_test.go
  config/config_test.go
  config/vault.go
  config/vault_test.go
  manager/runner.go
  watch/view.go
  watch/watcher.go
Labels: enhancement

#1326 use gnueabihf for 32-bit arm build
  Makefile
Labels: bug

#1324 alpine docker image doesn't run entrypoint as root
  CHANGELOG.md
  README.md
  docker/alpine/Dockerfile
  docker/alpine/docker-entrypoint.sh
Labels: bug, security
