Repository hashicorp/consul-template, pull requests merged in 2019-08, with the labels that each got.

#1243 Knob to blacklist some template functions
  README.md
  config/template.go
  manager/runner.go
  template/funcs.go
  template/template.go
  template/template_test.go
Labels: enhancement

#1249 add path sandboxing to `file` function
  README.md
  config/template.go
  config/template_test.go
  manager/runner.go
  template/funcs.go
  template/funcs_test.go
  template/template.go
  template/testdata/sandbox/path/to/bad-symlink
  template/testdata/sandbox/path/to/file
  template/testdata/sandbox/path/to/ok-symlink
Labels: enhancement

#1254 file sandbox: check but don't alter paths passed to 'file'
  README.md
  template/funcs.go
  template/funcs_test.go
Labels: enhancement, nomad

#1255 fix loop to work with different int types
  template/funcs.go
  template/template_test.go
Labels: bug

#1257 Issue1252: vault write broken
  dependency/vault_read_test.go
  dependency/vault_write.go
  dependency/vault_write_test.go
Labels: bug, vault

#1258 Updated readme to add space after name
  README.md
Labels: docs

#1260 Issue1198: error reading deleted secret
  dependency/dependency_test.go
  dependency/vault_read.go
  dependency/vault_read_test.go
Labels: bug, vault

#1265 change backup to use os.Link
  renderer/renderer.go
Labels: bug

#1269 fix vault retry logic on failed calls
  dependency/vault_common.go
  dependency/vault_common_test.go
  dependency/vault_read.go
  dependency/vault_read_test.go
  dependency/vault_token.go
  dependency/vault_write.go
  dependency/vault_write_test.go
Labels: bug, vault

#1271 fix backup to backup more than once
  renderer/renderer.go
  renderer/renderer_test.go
Labels: bug
