Repository hashicorp/consul-template, pull requests merged in 2020-04, with the labels that each got.

#1373 fix data race b/w start and kill
  child/child.go
Labels: bug

#1370 move render events to after template command
  README.md
  manager/runner.go
Labels: bug, vault

#1329 Make timeout for blocking query configurable
  README.md
  config/config.go
  config/config_test.go
  config/dedup.go
  config/dedup_test.go
  manager/runner.go
  watch/view.go
  watch/watcher.go
Labels: enhancement

#1367 Allow to set application name in syslog
  cli.go
  config/config_test.go
  config/syslog.go
  config/syslog_test.go
  logging/logging.go
Labels: enhancement

#1323 Add minimum and maximum math functions
  CHANGELOG.md
  README.md
  template/funcs.go
  template/template.go
  template/template_test.go
Labels: enhancement

#1327 Added sha256Hex function
  README.md
  template/funcs.go
  template/funcs_test.go
  template/template.go
Labels: enhancement

#1344 Add parseYAML helper
  README.md
  template/funcs.go
  template/template.go
  template/template_test.go
Labels: enhancement

#1375 Issue 1336 command doc fix
  README.md
Labels: docs

#1374 fix test compatibility issue with consul 1.7
  dependency/catalog_node_test.go
  dependency/catalog_nodes_test.go
  dependency/catalog_service_test.go
  dependency/consul_common_test.go
  dependency/health_service_test.go
Labels: bug, consul

#1320 consul namespaces support
  README.md
  config/consul.go
  config/consul_test.go
  dependency/client_set.go
  manager/runner.go
Labels: consul, enhancement
