Repository hashicorp/consul-template, pull requests merged in 2021-06, with the labels that each got.

#1476 rework logging and fix timestamp issue
  logging/logging.go
  logging/logging_test.go
  logging/syslog_test.go
Labels: bug

#1478 GitHub Actions based CI
  .github/workflows/ci.yml
Labels: enhancement

#1480 fix data race issue setting vault's default lease
  dependency/vault_common.go
  manager/runner.go
Labels: bug

#1483 remove stuff related to old build system
  Makefile
  docker/alpine/Dockerfile
  docker/alpine/docker-entrypoint.sh
  docker/light/Dockerfile
  docker/pristine/Dockerfile
  docker/scratch/Dockerfile
Labels: enhancement

#1484 new docker image build setup
  docker/Dockerfile
  docker/docker-entrypoint.sh
  docker/fetch-n-verify.sh
Labels: docker, enhancement

#1383 Simplify log level environment variable usage
  config/config.go
  config/config_test.go
  docs/observability.md
Labels: enhancement

#1487 don't send runtime signals to child process
  cli.go
  signals/signals_unix.go
  signals/signals_windows.go
Labels: enhancement
