Repository hashicorp/consul-template, pull requests merged in 2021-07, with the labels that each got.

#1494 Add setpgid for all called commands
  child/child.go
  child/child_test.go
Labels: enhancement

#1495 Add writeToFile function
  docs/templating-language.md
  template/funcs.go
  template/template.go
  template/template_test.go
Labels: enhancement, hashicat-update-required

#1496 replace shell parsing w/ direct shell call
  manager/command-prep.go
  manager/command-prep_windows.go
  manager/runner.go
  manager/runner_test.go
Labels: bug
