Repository hashicorp/consul-template, pull requests merged in 2021-05, with the labels that each got.

#1472 Improve template documentation
  README.md
  docs/templating-language.md
Labels: docs

#1468 fixes #1462, 'secrets' template function issue on Vault kv-v2 secrets engines
  dependency/vault_list.go
  dependency/vault_list_test.go
  dependency/vault_write.go
  dependency/vault_write_test.go
  docs/templating-language.md
Labels: enhancement, hashicat-update-required, vault

#1471 Removed special cases for ARM build in Makefile fixes #1404
  Makefile
Labels: enhancement

#1461 Fix/master: add envOrDefault helper
  docs/templating-language.md
  template/funcs.go
  template/template.go
  template/template_test.go
Labels: enhancement, hashicat-update-required

#1474 make connect and health service ids different
  dependency/health_service.go
  dependency/health_service_test.go
Labels: bug

#1473 fix issue with ownership when perms option is set
  renderer/renderer.go
Labels: bug
