Repository hashicorp/consul-template, pull requests merged in 2021-11, with the labels that each got.

#1529 Issue 1523 syslog fix
  logging/logging.go
  logging/logging_test.go
  logging/syslog_test.go
Labels: bug

#1532 support secret write queries w/ an empty write
  template/funcs.go
  template/template_test.go
Labels: bug, vault, hashicat-update-required, hashicat-update-complete

#1534 Logging to file
  README.md
  cli.go
  cli_test.go
  config/config.go
  config/config_test.go
  config/logfile.go
  docs/configuration.md
  docs/observability.md
  logging/logfile.go
  logging/logfile_test.go
  logging/logging.go
Labels: enhancement
