Repository hashicorp/consul-template, pull requests merged in 2021-04, with the labels that each got.

#1464 Adds an md5sum function
  docs/templating-language.md
  template/funcs.go
  template/funcs_test.go
  template/template.go
Labels: enhancement, hashicat-update-required

#1400 Adds support for service tagged addresses
  dependency/catalog_node_test.go
  dependency/catalog_services_test.go
  dependency/dependency_test.go
  dependency/health_service.go
  dependency/health_service_test.go
Labels: consul, enhancement, hashicat-update-required

#1385 Fixed typo and added example to README
  docs/templating-language.md
Labels: docs, waiting-reply

#1406 [feature] Add go-spew for debugging templates
  docs/templating-language.md
  go.mod
  go.sum
  template/funcs.go
  template/template.go
  template/template_test.go
Labels: enhancement, waiting-reply
