Repository hashicorp/consul-template, pull requests merged in 2022-06, with the labels that each got.

#1580 vault: support k8s auth method
  README.md
  config/config_test.go
  config/vault.go
  config/vault_test.go
  dependency/client_set.go
  dependency/client_set_test.go
  dependency/connect_ca_test.go
  dependency/vault_read_test.go
  go.mod
  go.sum
  manager/runner.go
  test/helpers.go
Labels: enhancement, hashicat-update-required

#1587 fix issue with debug printing of VaultConfig
  config/convert.go
  config/vault.go
  config/vault_test.go
Labels: bug

#1590 Issue 1588: pki cert renew bug + duration/renew logic fixes
  dependency/vault_common_test.go
  dependency/vault_pki.go
  dependency/vault_pki_test.go
Labels: bug

#1591 pkiCert now gets the Cert, Private key and CA
  dependency/vault_pki.go
  dependency/vault_pki_test.go
  docs/templating-language.md
  template/template_test.go
Labels: enhancement, vault, hashicat-update-required
