Repository hashicorp/consul-template, pull requests merged in 2022-04, with the labels that each got.

#1559 add new pkiCert template function
  dependency/dependency_test.go
  dependency/vault_common_test.go
  dependency/vault_pki.go
  dependency/vault_pki_test.go
  dependency/vault_read_test.go
  docs/templating-language.md
  template/funcs.go
  template/template.go
  template/template_test.go
Labels: bug, vault

#1502 set sid for child process group
  child/child.go
  child/child_test.go
  child/sys_nix.go
  child/sys_windows.go
Labels: enhancement

#1510 Add transport section to configuration file
  docs/configuration.md
Labels: docs, needs-cla-signature

#1562 Remove writeToFile reliance on cgo/$USER for UID/GID detection
  template/funcs.go
Labels: enhancement

#1563 fix name/use of confusing Block flag
  dependency/connect_ca.go
  dependency/connect_leaf.go
  dependency/dependency.go
  dependency/kv_get.go
  watch/view.go
Labels: enhancement, consul, hashicat-update-required

#1558 Added trim functions
  docs/templating-language.md
  template/funcs.go
  template/template.go
  template/template_test.go
Labels: enhancement, hashicat-update-required

#1573 fix bug with 2 templates, same ID, different paths
  manager/runner.go
  manager/runner_test.go
  template/template.go
Labels: bug

#1565 Add Nomad Service Discovery Support
  .circleci/config.yml
  config/config.go
  config/config_test.go
  config/mapstructure_test.go
  config/nomad.go
  config/nomad_test.go
  dependency/client_set.go
  dependency/dependency.go
  dependency/dependency_test.go
  dependency/nomad_service.go
  dependency/nomad_service_test.go
  dependency/nomad_services.go
  dependency/nomad_services_test.go
  go.mod
  go.sum
  manager/runner.go
  signals/mapstructure_test.go
  template/nomad_funcs.go
  template/template.go
  test/testdata/nomad.json
Labels: enhancement, nomad, hashicat-update-required

#1574 docs on shell + signal handling for exec mode
  README.md
Labels: docs

#1575 reduce os.Signal noise
  cli.go
  signals/signals.go
  signals/signals_unix.go
  signals/signals_windows.go
Labels: bug

#1576 convert project to CRT release process
  .github/CODEOWNERS
  .github/workflows/build.yml
  .release/ci.hcl
  .release/docker-entrypoint.sh
  .release/security-scan.hcl
  Dockerfile
  Makefile
  docker/Dockerfile
  docker/fetch-n-verify.sh
Labels: enhancement
