Repository hashicorp/consul-template, pull requests merged in 2022-10, with the labels that each got.

#1653 Ensure that nomad config is copied over when not nil
  .github/workflows/ci.yml
  config/config.go
  manager/runner_test.go
Labels: bug, nomad

#1652 isChownNeeded bad when only user/group (!both) set
  renderer/file_ownership.go
  renderer/renderer_test.go
Labels: bug

#1632 Support Nomad Variables
  config/nomad_test.go
  dependency/client_set.go
  dependency/dependency.go
  dependency/dependency_test.go
  dependency/nomad_var_get.go
  dependency/nomad_var_get_test.go
  dependency/nomad_var_list.go
  dependency/nomad_var_list_test.go
  dependency/nomad_var_structs.go
  docs/templating-language.md
  go.mod
  go.sum
  manager/dedup_test.go
  manager/runner.go
  renderer/renderer_test.go
  template/nomad_funcs.go
  template/template.go
  template/template_test.go
  watch/vault_token_test.go
Labels: enhancement, nomad
