Repository hashicorp/consul-template, pull requests merged in 2022-08, with the labels that each got.

#1610 Issue 1428 fix no reload signal
  child/child.go
  child/child_test.go
  cli_test.go
  config/config_test.go
  config/convert.go
  config/convert_test.go
  signals/mapstructure.go
  signals/nil.go
  signals/signals.go
  signals/signals_unix.go
  signals/signals_windows.go
Labels: bug

#1611 make sure pki IDs are unique
  dependency/vault_pki.go
  dependency/vault_pki_test.go
  template/template_test.go
Labels: bug, hashicat-update-required

#1606 Add NomadConfig Retry
  README.md
  config/nomad.go
  config/nomad_test.go
  docs/configuration.md
  manager/runner.go
  watch/watcher.go
Labels: enhancement, nomad

#1613 filter out vault secrets from template errors
  template/template.go
  template/template_test.go
Labels: bug, vault, security

#1630 fix explodeMap example error in doc
  docs/templating-language.md
Labels: docs

#1628 Updated Makefile to work when Consul-Template is in a Go Workspace
  Makefile
Labels: go-modules
