Repository hashicorp/consul-template, pull requests merged in 2022-11, with the labels that each got.

#1662 fix: user set in dockerfile
  Dockerfile
Labels: bug, docker

#1664 Enable template function splitToMap
  docs/templating-language.md
  template/funcs.go
  template/template.go
  template/template_test.go
Labels: enhancement

#1668 use internal signal implementation for force kill
  child/child.go
Labels: bug
