Repository hashicorp/consul-template, pull requests merged in 2022-05, with the labels that each got.

#1578 sort: use strictly less-than for less implementations
  config/nomad.go
  dependency/catalog_node.go
  dependency/catalog_nodes.go
  dependency/catalog_services.go
  dependency/health_service.go
  dependency/nomad_service.go
  dependency/nomad_services.go
  template/brain.go
Labels: bug, hashicat-update-required

#1581 new promote-staging config entry
  .release/ci.hcl
Labels: bug

#1579 nomad: add support for querying consistent subset of services
  dependency/dependency.go
  dependency/nomad_service.go
  dependency/nomad_service_test.go
  dependency/nomad_services_test.go
  docs/templating-language.md
  template/nomad_funcs.go
Labels: enhancement
